import * as THREE from 'three';

export const state = {
  narrators: [],
  transmissions: [],
  hadiths: [],
  scene: null,
  camera: null,
  renderer: null,
  clock: null,
  starPoints: null,
  selLines: null,
  bgParticles: null,
  raycaster: null,
  mouse: null,
  selId: null,
  hovId: null,
  filter: 'all',
  view: '3d',
  autoOn: false,
  posMap: {},
  idxMap: {},
  labelDivs: [],
  indexOfId: {},
  pathIds: null,
  hadith: null,
  mode: 'narrators',
  narById: new Map(),
  spherical: new THREE.Spherical(620, Math.PI / 2, 0),
  targetSpherical: new THREE.Spherical(620, Math.PI / 2, 0),
  panTarget: new THREE.Vector3(0, 0, 0),
  panCurrent: new THREE.Vector3(0, 0, 0),
  flyAnim: null,
  ERA_MIN: 1,
  ERA_MAX: 950,
  TL_MIN: 1,
  TL_MAX: 950,
};
