/**
 * Additional reference data: well-known narrators of the six books and the
 * Muwatta with their death year (AH), layer and home town.
 *
 * Sources: Taqrib al-Tahdhib, Tahdhib al-Kamal, Siyar A'lam al-Nubala. Years
 * follow the most commonly cited date; ±2 years is possible for a few.
 *
 * `names` lists the forms under which the narrator appears in isnads. Short
 * forms that designate several people (سفيان, يحيى, هشام, حماد, عبد الله…) are
 * deliberately NOT listed: they stay undated and get an interpolated year.
 */
export const EXTRA_NARRATORS = [
  // ── Compilers ──────────────────────────────────────────────────────────
  { names: ['البخاري', 'محمد بن اسماعيل البخاري'], latin: 'al-Bukhari', death: 256, gen: 'muhaddith', origin: 'بخارى' },
  { names: ['مسلم', 'مسلم بن الحجاج'], latin: 'Muslim ibn al-Hajjaj', death: 261, gen: 'muhaddith', origin: 'نيسابور' },
  { names: ['ابو داود', 'ابو داود السجستاني', 'سليمان بن الاشعث'], latin: 'Abu Dawud', death: 275, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['الترمذي', 'محمد بن عيسي الترمذي'], latin: 'al-Tirmidhi', death: 279, gen: 'muhaddith', origin: 'خراسان' },
  { names: ['النسايي', 'احمد بن شعيب النسايي'], latin: 'al-Nasa\'i', death: 303, gen: 'muhaddith', origin: 'خراسان' },
  { names: ['ابن ماجه', 'محمد بن يزيد بن ماجه'], latin: 'Ibn Majah', death: 273, gen: 'muhaddith', origin: 'قزوين' },
  { names: ['مالك', 'مالك بن انس'], latin: 'Malik ibn Anas', death: 179, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['يحيي بن يحيي الليثي'], latin: 'Yahya ibn Yahya al-Laythi', death: 234, gen: 'muhaddith', origin: 'الأندلس' },

  // ── Companions ─────────────────────────────────────────────────────────
  { names: ['ابو هريره', 'عبد الرحمن بن صخر'], latin: 'Abu Hurayra', death: 59, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عبد الله بن عمر', 'ابن عمر', 'عبد الله بن عمر بن الخطاب'], latin: 'Abdullah ibn Umar', death: 73, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عايشه', 'عايشه بنت ابي بكر'], latin: 'Aisha', death: 58, gen: 'sahabi', origin: 'المدينة' },
  { names: ['انس', 'انس بن مالك'], latin: 'Anas ibn Malik', death: 93, gen: 'sahabi', origin: 'البصرة' },
  { names: ['ابن عباس', 'عبد الله بن عباس'], latin: 'Abdullah ibn Abbas', death: 68, gen: 'sahabi', origin: 'مكة' },
  { names: ['جابر', 'جابر بن عبد الله', 'جابر بن عبد الله الانصاري'], latin: 'Jabir ibn Abdullah', death: 78, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابن مسعود', 'عبد الله بن مسعود'], latin: 'Abdullah ibn Mas\'ud', death: 32, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['ابو سعيد الخدري', 'ابو سعيد'], latin: 'Abu Sa\'id al-Khudri', death: 74, gen: 'sahabi', origin: 'المدينة' },
  { names: ['علي', 'علي بن ابي طالب'], latin: 'Ali ibn Abi Talib', death: 40, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['ابو بكر', 'ابو بكر الصديق'], latin: 'Abu Bakr al-Siddiq', death: 13, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عمر', 'عمر بن الخطاب'], latin: 'Umar ibn al-Khattab', death: 23, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عثمان', 'عثمان بن عفان'], latin: 'Uthman ibn Affan', death: 35, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو موسي', 'ابو موسي الاشعري', 'عبد الله بن قيس'], latin: 'Abu Musa al-Ash\'ari', death: 44, gen: 'sahabi', origin: 'البصرة' },
  { names: ['معاويه', 'معاويه بن ابي سفيان'], latin: 'Mu\'awiya', death: 60, gen: 'sahabi', origin: 'الشام' },
  { names: ['سعد', 'سعد بن ابي وقاص'], latin: 'Sa\'d ibn Abi Waqqas', death: 55, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو ذر', 'ابو ذر الغفاري'], latin: 'Abu Dharr', death: 32, gen: 'sahabi', origin: 'المدينة' },
  { names: ['زيد بن ثابت'], latin: 'Zayd ibn Thabit', death: 45, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو ايوب', 'ابو ايوب الانصاري'], latin: 'Abu Ayyub al-Ansari', death: 52, gen: 'sahabi', origin: 'المدينة' },
  { names: ['سهل بن سعد', 'سهل بن سعد الساعدي'], latin: 'Sahl ibn Sa\'d', death: 91, gen: 'sahabi', origin: 'المدينة' },
  { names: ['البراء', 'البراء بن عازب'], latin: 'al-Bara\' ibn Azib', death: 72, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['ابو الدرداء'], latin: 'Abu al-Darda\'', death: 32, gen: 'sahabi', origin: 'الشام' },
  { names: ['حذيفه', 'حذيفه بن اليمان'], latin: 'Hudhayfa', death: 36, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['عمران بن حصين'], latin: 'Imran ibn Husayn', death: 52, gen: 'sahabi', origin: 'البصرة' },
  { names: ['المغيره بن شعبه'], latin: 'al-Mughira ibn Shu\'ba', death: 50, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['اسامه بن زيد'], latin: 'Usama ibn Zayd', death: 54, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ام سلمه'], latin: 'Umm Salama', death: 62, gen: 'sahabi', origin: 'المدينة' },
  { names: ['حفصه', 'حفصه بنت عمر'], latin: 'Hafsa', death: 45, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عبد الله بن عمرو', 'عبد الله بن عمرو بن العاص'], latin: 'Abdullah ibn Amr', death: 65, gen: 'sahabi', origin: 'مصر' },
  { names: ['ابو قتاده', 'ابو قتاده الانصاري'], latin: 'Abu Qatada', death: 54, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو مسعود', 'ابو مسعود الانصاري', 'عقبه بن عمرو'], latin: 'Abu Mas\'ud al-Ansari', death: 40, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['جرير بن عبد الله', 'جرير بن عبد الله البجلي'], latin: 'Jarir ibn Abdullah', death: 51, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['النعمان بن بشير'], latin: 'al-Nu\'man ibn Bashir', death: 64, gen: 'sahabi', origin: 'الشام' },
  { names: ['عبد الله بن الزبير', 'ابن الزبير'], latin: 'Abdullah ibn al-Zubayr', death: 73, gen: 'sahabi', origin: 'مكة' },
  { names: ['ابو بكره'], latin: 'Abu Bakra', death: 52, gen: 'sahabi', origin: 'البصرة' },
  { names: ['سلمان', 'سلمان الفارسي'], latin: 'Salman al-Farisi', death: 36, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['عبد الرحمن بن عوف'], latin: 'Abd al-Rahman ibn Awf', death: 32, gen: 'sahabi', origin: 'المدينة' },
  { names: ['الزبير', 'الزبير بن العوام'], latin: 'al-Zubayr ibn al-Awwam', death: 36, gen: 'sahabi', origin: 'المدينة' },
  { names: ['طلحه بن عبيد الله'], latin: 'Talha ibn Ubaydullah', death: 36, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عمار', 'عمار بن ياسر'], latin: 'Ammar ibn Yasir', death: 37, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['ابي بن كعب', 'ابي'], latin: 'Ubayy ibn Ka\'b', death: 30, gen: 'sahabi', origin: 'المدينة' },
  { names: ['معاذ بن جبل', 'معاذ'], latin: 'Mu\'adh ibn Jabal', death: 18, gen: 'sahabi', origin: 'الشام' },
  { names: ['عمرو بن العاص'], latin: 'Amr ibn al-As', death: 43, gen: 'sahabi', origin: 'مصر' },
  { names: ['كعب بن مالك'], latin: 'Ka\'b ibn Malik', death: 50, gen: 'sahabi', origin: 'المدينة' },
  { names: ['كعب الاحبار', 'كعب بن ماتع', 'كعب بن ماتع الحميري'], latin: 'Ka\'b al-Ahbar', death: 32, gen: 'tabii', origin: 'الشام' },
  { names: ['ابو برزه', 'ابو برزه الاسلمي'], latin: 'Abu Barza al-Aslami', death: 65, gen: 'sahabi', origin: 'البصرة' },
  { names: ['عباده بن الصامت'], latin: 'Ubada ibn al-Samit', death: 34, gen: 'sahabi', origin: 'الشام' },
  { names: ['ابو امامه', 'ابو امامه الباهلي'], latin: 'Abu Umama al-Bahili', death: 86, gen: 'sahabi', origin: 'الشام' },
  { names: ['سلمه بن الاكوع'], latin: 'Salama ibn al-Akwa\'', death: 74, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو الطفيل', 'ابو الطفيل عامر بن واثله'], latin: 'Abu al-Tufayl', death: 100, gen: 'sahabi', origin: 'مكة' },
  { names: ['رافع بن خديج'], latin: 'Rafi\' ibn Khadij', death: 74, gen: 'sahabi', origin: 'المدينة' },
  { names: ['زيد بن ارقم'], latin: 'Zayd ibn Arqam', death: 68, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['عبد الله بن ابي اوفي', 'ابن ابي اوفي'], latin: 'Abdullah ibn Abi Awfa', death: 87, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['جابر بن سمره'], latin: 'Jabir ibn Samura', death: 74, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['ابو جحيفه'], latin: 'Abu Juhayfa', death: 74, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['المسور بن مخرمه'], latin: 'al-Miswar ibn Makhrama', death: 64, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عقبه بن عامر', 'عقبه بن عامر الجهني'], latin: 'Uqba ibn Amir', death: 58, gen: 'sahabi', origin: 'مصر' },
  { names: ['ثوبان'], latin: 'Thawban', death: 54, gen: 'sahabi', origin: 'الشام' },
  { names: ['حكيم بن حزام'], latin: 'Hakim ibn Hizam', death: 54, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو حميد الساعدي'], latin: 'Abu Humayd al-Sa\'idi', death: 60, gen: 'sahabi', origin: 'المدينة' },
  { names: ['اسماء بنت ابي بكر', 'اسماء'], latin: 'Asma\' bint Abi Bakr', death: 73, gen: 'sahabi', origin: 'مكة' },
  { names: ['ميمونه'], latin: 'Maymuna', death: 51, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ام حبيبه'], latin: 'Umm Habiba', death: 44, gen: 'sahabi', origin: 'المدينة' },
  { names: ['صفيه بنت حيي'], latin: 'Safiyya', death: 50, gen: 'sahabi', origin: 'المدينة' },
  { names: ['بريده', 'بريده بن الحصيب', 'بريده الاسلمي'], latin: 'Burayda ibn al-Husayb', death: 63, gen: 'sahabi', origin: 'خراسان' },
  { names: ['ابو رافع'], latin: 'Abu Rafi\'', death: 40, gen: 'sahabi', origin: 'المدينة' },
  { names: ['بلال', 'بلال بن رباح'], latin: 'Bilal', death: 20, gen: 'sahabi', origin: 'الشام' },
  { names: ['خباب', 'خباب بن الارت'], latin: 'Khabbab ibn al-Aratt', death: 37, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['ابو الدرداء عويمر'], latin: 'Abu al-Darda\'', death: 32, gen: 'sahabi', origin: 'الشام' },
  { names: ['واثله بن الاسقع'], latin: 'Wathila ibn al-Asqa\'', death: 83, gen: 'sahabi', origin: 'الشام' },
  { names: ['عبد الله بن بسر'], latin: 'Abdullah ibn Busr', death: 88, gen: 'sahabi', origin: 'الشام' },
  { names: ['ابن الزبير عبد الله'], latin: 'Abdullah ibn al-Zubayr', death: 73, gen: 'sahabi', origin: 'مكة' },
  { names: ['عبد الله بن عمرو بن العاص'], latin: 'Abdullah ibn Amr ibn al-As', death: 65, gen: 'sahabi', origin: 'مصر' },
  { names: ['ابو الدرداء'], latin: 'Abu al-Darda\'', death: 32, gen: 'sahabi', origin: 'الشام' },
  { names: ['عبد الله بن عمر بن الخطاب'], latin: 'Abdullah ibn Umar', death: 73, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو رمثه'], latin: 'Abu Rimtha', death: 60, gen: 'sahabi', origin: 'الكوفة' },
  { names: ['ابن عمرو عبد الله'], latin: 'Abdullah ibn Amr', death: 65, gen: 'sahabi', origin: 'مصر' },
  { names: ['عمرو بن اميه الضمري'], latin: 'Amr ibn Umayya', death: 60, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو اسيد الساعدي'], latin: 'Abu Usayd al-Sa\'idi', death: 60, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عبد الله بن سلام'], latin: 'Abdullah ibn Salam', death: 43, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابو شريح الخزاعي'], latin: 'Abu Shurayh al-Khuza\'i', death: 68, gen: 'sahabi', origin: 'المدينة' },
  { names: ['عبد الله بن جعفر'], latin: 'Abdullah ibn Ja\'far', death: 80, gen: 'sahabi', origin: 'المدينة' },
  { names: ['ابن الزبير عروه'], latin: 'Urwa', death: 94, gen: 'tabii', origin: 'المدينة' },

  // ── Successors (tabi'un) ───────────────────────────────────────────────
  { names: ['سعيد بن المسيب', 'ابن المسيب'], latin: 'Sa\'id ibn al-Musayyib', death: 94, gen: 'tabii', origin: 'المدينة' },
  { names: ['نافع', 'نافع مولي ابن عمر'], latin: 'Nafi\' mawla Ibn Umar', death: 117, gen: 'tabii', origin: 'المدينة' },
  { names: ['عروه', 'عروه بن الزبير'], latin: 'Urwa ibn al-Zubayr', death: 94, gen: 'tabii', origin: 'المدينة' },
  { names: ['الزهري', 'ابن شهاب', 'ابن شهاب الزهري', 'محمد بن مسلم بن شهاب', 'محمد بن شهاب'], latin: 'Ibn Shihab al-Zuhri', death: 124, gen: 'tabii', origin: 'المدينة' },
  { names: ['الحسن', 'الحسن البصري'], latin: 'al-Hasan al-Basri', death: 110, gen: 'tabii', origin: 'البصرة' },
  { names: ['ابن سيرين', 'محمد بن سيرين', 'محمد'], latin: 'Ibn Sirin', death: 110, gen: 'tabii', origin: 'البصرة', ambiguous: ['محمد'] },
  { names: ['عطاء', 'عطاء بن ابي رباح'], latin: 'Ata\' ibn Abi Rabah', death: 114, gen: 'tabii', origin: 'مكة' },
  { names: ['مجاهد', 'مجاهد بن جبر'], latin: 'Mujahid', death: 104, gen: 'tabii', origin: 'مكة' },
  { names: ['ابراهيم', 'ابراهيم النخعي'], latin: 'Ibrahim al-Nakha\'i', death: 96, gen: 'tabii', origin: 'الكوفة', ambiguous: ['ابراهيم'] },
  { names: ['الشعبي', 'عامر الشعبي', 'عامر'], latin: 'al-Sha\'bi', death: 103, gen: 'tabii', origin: 'الكوفة', ambiguous: ['عامر'] },
  { names: ['علقمه', 'علقمه بن قيس'], latin: 'Alqama ibn Qays', death: 62, gen: 'tabii', origin: 'الكوفة' },
  { names: ['الاسود', 'الاسود بن يزيد'], latin: 'al-Aswad ibn Yazid', death: 75, gen: 'tabii', origin: 'الكوفة' },
  { names: ['ابو وايل', 'شقيق بن سلمه'], latin: 'Abu Wa\'il', death: 82, gen: 'tabii', origin: 'الكوفة' },
  { names: ['زر', 'زر بن حبيش'], latin: 'Zirr ibn Hubaysh', death: 82, gen: 'tabii', origin: 'الكوفة' },
  { names: ['ابو صالح السمان', 'ذكوان', 'ذكوان ابو صالح'], latin: 'Abu Salih al-Samman', death: 101, gen: 'tabii', origin: 'المدينة' },
  { names: ['الاعرج', 'عبد الرحمن بن هرمز', 'عبد الرحمن بن هرمز الاعرج'], latin: 'al-A\'raj', death: 117, gen: 'tabii', origin: 'المدينة' },
  { names: ['ابو الزناد', 'عبد الله بن ذكوان'], latin: 'Abu al-Zinad', death: 130, gen: 'tabii', origin: 'المدينة' },
  { names: ['سالم', 'سالم بن عبد الله', 'سالم بن عبد الله بن عمر'], latin: 'Salim ibn Abdullah', death: 106, gen: 'tabii', origin: 'المدينة' },
  { names: ['القاسم', 'القاسم بن محمد'], latin: 'al-Qasim ibn Muhammad', death: 106, gen: 'tabii', origin: 'المدينة' },
  { names: ['عبيد الله بن عبد الله', 'عبيد الله بن عبد الله بن عتبه', 'عبيد الله بن عبد الله بن عتبه بن مسعود'], latin: 'Ubaydullah ibn Abdullah ibn Utba', death: 98, gen: 'tabii', origin: 'المدينة' },
  { names: ['ابو سلمه', 'ابو سلمه بن عبد الرحمن'], latin: 'Abu Salama ibn Abd al-Rahman', death: 94, gen: 'tabii', origin: 'المدينة' },
  { names: ['حميد بن عبد الرحمن', 'حميد بن عبد الرحمن بن عوف'], latin: 'Humayd ibn Abd al-Rahman', death: 95, gen: 'tabii', origin: 'المدينة' },
  { names: ['خارجه بن زيد'], latin: 'Kharija ibn Zayd', death: 100, gen: 'tabii', origin: 'المدينة' },
  { names: ['سليمان بن يسار'], latin: 'Sulayman ibn Yasar', death: 107, gen: 'tabii', origin: 'المدينة' },
  { names: ['عطاء بن يسار'], latin: 'Ata\' ibn Yasar', death: 103, gen: 'tabii', origin: 'المدينة' },
  { names: ['عكرمه', 'عكرمه مولي ابن عباس'], latin: 'Ikrima', death: 105, gen: 'tabii', origin: 'المدينة' },
  { names: ['طاوس', 'طاوس بن كيسان'], latin: 'Tawus ibn Kaysan', death: 106, gen: 'tabii', origin: 'اليمن' },
  { names: ['سعيد بن جبير'], latin: 'Sa\'id ibn Jubayr', death: 95, gen: 'tabii', origin: 'الكوفة' },
  { names: ['ابو العاليه', 'رفيع ابو العاليه'], latin: 'Abu al-Aliya', death: 90, gen: 'tabii', origin: 'البصرة' },
  { names: ['قتاده', 'قتاده بن دعامه'], latin: 'Qatada', death: 117, gen: 'tabii', origin: 'البصرة' },
  { names: ['ثابت', 'ثابت البناني'], latin: 'Thabit al-Bunani', death: 127, gen: 'tabii', origin: 'البصرة' },
  { names: ['محمد بن المنكدر', 'ابن المنكدر'], latin: 'Muhammad ibn al-Munkadir', death: 130, gen: 'tabii', origin: 'المدينة' },
  { names: ['عمرو بن دينار'], latin: 'Amr ibn Dinar', death: 126, gen: 'tabii', origin: 'مكة' },
  { names: ['ابو الزبير', 'ابو الزبير المكي'], latin: 'Abu al-Zubayr al-Makki', death: 128, gen: 'tabii', origin: 'مكة' },
  { names: ['ابو اسحاق', 'ابو اسحاق السبيعي'], latin: 'Abu Ishaq al-Sabi\'i', death: 127, gen: 'tabii', origin: 'الكوفة' },
  { names: ['منصور', 'منصور بن المعتمر'], latin: 'Mansur ibn al-Mu\'tamir', death: 132, gen: 'tabii', origin: 'الكوفة' },
  { names: ['الاعمش', 'سليمان الاعمش', 'سليمان بن مهران'], latin: 'al-A\'mash', death: 148, gen: 'tabii', origin: 'الكوفة' },
  { names: ['حماد بن ابي سليمان'], latin: 'Hammad ibn Abi Sulayman', death: 120, gen: 'tabii', origin: 'الكوفة' },
  { names: ['مكحول'], latin: 'Makhul', death: 113, gen: 'tabii', origin: 'الشام' },
  { names: ['بسر بن سعيد'], latin: 'Busr ibn Sa\'id', death: 100, gen: 'tabii', origin: 'المدينة' },
  { names: ['عمرو بن شعيب'], latin: 'Amr ibn Shu\'ayb', death: 118, gen: 'tabii', origin: 'الطائف' },
  { names: ['عبد الرحمن بن ابي ليلي'], latin: 'Abd al-Rahman ibn Abi Layla', death: 83, gen: 'tabii', origin: 'الكوفة' },
  { names: ['سعيد المقبري', 'سعيد بن ابي سعيد', 'سعيد بن ابي سعيد المقبري'], latin: 'Sa\'id al-Maqburi', death: 123, gen: 'tabii', origin: 'المدينة' },
  { names: ['عبد الله بن دينار'], latin: 'Abdullah ibn Dinar', death: 127, gen: 'tabii', origin: 'المدينة' },
  { names: ['زيد بن اسلم'], latin: 'Zayd ibn Aslam', death: 136, gen: 'tabii', origin: 'المدينة' },
  { names: ['ربيعه', 'ربيعه بن ابي عبد الرحمن', 'ربيعه الراي'], latin: 'Rabi\'a al-Ra\'y', death: 136, gen: 'tabii', origin: 'المدينة' },
  { names: ['يحيي بن سعيد الانصاري', 'يحيي بن سعيد بن قيس'], latin: 'Yahya ibn Sa\'id al-Ansari', death: 143, gen: 'tabii', origin: 'المدينة' },
  { names: ['هشام بن عروه'], latin: 'Hisham ibn Urwa', death: 146, gen: 'tabii', origin: 'المدينة' },
  { names: ['صالح بن كيسان'], latin: 'Salih ibn Kaysan', death: 140, gen: 'tabii', origin: 'المدينة' },
  { names: ['موسي بن عقبه'], latin: 'Musa ibn Uqba', death: 141, gen: 'tabii', origin: 'المدينة' },
  { names: ['عبيد الله بن عمر', 'عبيد الله بن عمر العمري'], latin: 'Ubaydullah ibn Umar al-Umari', death: 147, gen: 'tabii', origin: 'المدينة' },
  { names: ['ايوب السختياني', 'ايوب بن ابي تميمه'], latin: 'Ayyub al-Sakhtiyani', death: 131, gen: 'tabii', origin: 'البصرة' },
  { names: ['يونس بن عبيد'], latin: 'Yunus ibn Ubayd', death: 139, gen: 'tabii', origin: 'البصرة' },
  { names: ['خالد الحذاء', 'خالد بن مهران'], latin: 'Khalid al-Hadhdha\'', death: 141, gen: 'tabii', origin: 'البصرة' },
  { names: ['داود بن ابي هند'], latin: 'Dawud ibn Abi Hind', death: 140, gen: 'tabii', origin: 'البصرة' },
  { names: ['عاصم الاحول', 'عاصم بن سليمان'], latin: 'Asim al-Ahwal', death: 142, gen: 'tabii', origin: 'البصرة' },
  { names: ['سليمان التيمي', 'سليمان بن طرخان'], latin: 'Sulayman al-Taymi', death: 143, gen: 'tabii', origin: 'البصرة' },
  { names: ['حميد', 'حميد الطويل'], latin: 'Humayd al-Tawil', death: 143, gen: 'tabii', origin: 'البصرة' },
  { names: ['عبد العزيز بن صهيب'], latin: 'Abd al-Aziz ibn Suhayb', death: 130, gen: 'tabii', origin: 'البصرة' },
  { names: ['عمرو بن مره'], latin: 'Amr ibn Murra', death: 118, gen: 'tabii', origin: 'الكوفة' },
  { names: ['ابو برده', 'ابو برده بن ابي موسي'], latin: 'Abu Burda ibn Abi Musa', death: 104, gen: 'tabii', origin: 'الكوفة' },
  { names: ['ابو حازم', 'ابو حازم الاعرج', 'سلمه بن دينار'], latin: 'Abu Hazim al-A\'raj', death: 140, gen: 'tabii', origin: 'المدينة' },
  { names: ['يزيد بن ابي حبيب'], latin: 'Yazid ibn Abi Habib', death: 128, gen: 'tabii', origin: 'مصر' },
  { names: ['بكير بن الاشج', 'بكير بن عبد الله بن الاشج'], latin: 'Bukayr ibn al-Ashajj', death: 127, gen: 'tabii', origin: 'مصر' },
  { names: ['عاصم بن بهدله', 'عاصم بن ابي النجود'], latin: 'Asim ibn Bahdala', death: 128, gen: 'tabii', origin: 'الكوفة' },
  { names: ['حصين', 'حصين بن عبد الرحمن'], latin: 'Husayn ibn Abd al-Rahman', death: 136, gen: 'tabii', origin: 'الكوفة' },
  { names: ['مغيره', 'مغيره بن مقسم'], latin: 'Mughira ibn Miqsam', death: 136, gen: 'tabii', origin: 'الكوفة' },
  { names: ['عمرو بن يحيي', 'عمرو بن يحيي المازني'], latin: 'Amr ibn Yahya al-Mazini', death: 140, gen: 'tabii', origin: 'المدينة' },
  { names: ['اسماعيل بن ابي خالد'], latin: 'Isma\'il ibn Abi Khalid', death: 146, gen: 'tabii', origin: 'الكوفة' },
  { names: ['عقيل', 'عقيل بن خالد'], latin: 'Uqayl ibn Khalid', death: 144, gen: 'tabii', origin: 'مصر' },
  { names: ['يونس بن يزيد', 'يونس بن يزيد الايلي'], latin: 'Yunus ibn Yazid al-Ayli', death: 159, gen: 'muhaddith', origin: 'مصر' },
  { names: ['شعيب', 'شعيب بن ابي حمزه'], latin: 'Shu\'ayb ibn Abi Hamza', death: 162, gen: 'muhaddith', origin: 'الشام' },
  { names: ['معمر', 'معمر بن راشد'], latin: 'Ma\'mar ibn Rashid', death: 153, gen: 'muhaddith', origin: 'اليمن' },
  { names: ['ابن جريج', 'عبد الملك بن جريج', 'عبد الملك بن عبد العزيز بن جريج'], latin: 'Ibn Jurayj', death: 150, gen: 'muhaddith', origin: 'مكة' },
  { names: ['ابن اسحاق', 'محمد بن اسحاق'], latin: 'Ibn Ishaq', death: 151, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['الاوزاعي', 'عبد الرحمن بن عمرو الاوزاعي'], latin: 'al-Awza\'i', death: 157, gen: 'muhaddith', origin: 'الشام' },
  { names: ['ابن ابي ذيب', 'محمد بن عبد الرحمن بن ابي ذيب'], latin: 'Ibn Abi Dhi\'b', death: 158, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['شعبه', 'شعبه بن الحجاج'], latin: 'Shu\'ba ibn al-Hajjaj', death: 160, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['سفيان الثوري', 'الثوري', 'سفيان بن سعيد'], latin: 'Sufyan al-Thawri', death: 161, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['اسراييل', 'اسراييل بن يونس'], latin: 'Isra\'il ibn Yunus', death: 162, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['مسعر', 'مسعر بن كدام'], latin: 'Mis\'ar ibn Kidam', death: 155, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['هشام الدستوايي', 'هشام بن ابي عبد الله'], latin: 'Hisham al-Dastuwa\'i', death: 154, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['سعيد بن ابي عروبه', 'ابن ابي عروبه'], latin: 'Sa\'id ibn Abi Aruba', death: 156, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['همام', 'همام بن يحيي'], latin: 'Hammam ibn Yahya', death: 164, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['حماد بن سلمه'], latin: 'Hammad ibn Salama', death: 167, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['جرير بن حازم'], latin: 'Jarir ibn Hazim', death: 170, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['زهير بن معاويه', 'زهير بن معاويه الجعفي'], latin: 'Zuhayr ibn Mu\'awiya', death: 173, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['الليث', 'الليث بن سعد'], latin: 'al-Layth ibn Sa\'d', death: 175, gen: 'muhaddith', origin: 'مصر' },
  { names: ['ابو عوانه', 'وضاح بن عبد الله'], latin: 'Abu Awana', death: 176, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['شريك', 'شريك بن عبد الله', 'شريك بن عبد الله النخعي'], latin: 'Sharik ibn Abdullah', death: 177, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['حماد بن زيد'], latin: 'Hammad ibn Zayd', death: 179, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['ابو الاحوص', 'سلام بن سليم'], latin: 'Abu al-Ahwas Sallam ibn Sulaym', death: 179, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['عبد الوارث', 'عبد الوارث بن سعيد'], latin: 'Abd al-Warith ibn Sa\'id', death: 180, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['عبد الله بن المبارك', 'ابن المبارك'], latin: 'Abdullah ibn al-Mubarak', death: 181, gen: 'muhaddith', origin: 'خراسان' },
  { names: ['يزيد بن زريع'], latin: 'Yazid ibn Zuray\'', death: 182, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['هشيم', 'هشيم بن بشير'], latin: 'Hushaym ibn Bashir', death: 183, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['يحيي بن زكريا بن ابي زايده', 'ابن ابي زايده'], latin: 'Yahya ibn Zakariyya ibn Abi Za\'ida', death: 184, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['ابراهيم بن سعد'], latin: 'Ibrahim ibn Sa\'d', death: 185, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['خالد بن الحارث'], latin: 'Khalid ibn al-Harith', death: 186, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['عيسي بن يونس'], latin: 'Isa ibn Yunus', death: 187, gen: 'muhaddith', origin: 'الشام' },
  { names: ['عبده بن سليمان'], latin: 'Abda ibn Sulayman', death: 188, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['جرير بن عبد الحميد'], latin: 'Jarir ibn Abd al-Hamid', death: 188, gen: 'muhaddith', origin: 'الري' },
  { names: ['علي بن مسهر'], latin: 'Ali ibn Mushir', death: 189, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['عبد الرحمن بن القاسم'], latin: 'Abd al-Rahman ibn al-Qasim', death: 191, gen: 'muhaddith', origin: 'مصر' },
  { names: ['عبد الله بن ادريس', 'ابن ادريس'], latin: 'Abdullah ibn Idris', death: 192, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['مروان بن معاويه', 'مروان بن معاويه الفزاري'], latin: 'Marwan ibn Mu\'awiya al-Fazari', death: 193, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['ابن عليه', 'اسماعيل بن عليه', 'اسماعيل بن ابراهيم بن عليه', 'اسماعيل بن ابراهيم'], latin: 'Isma\'il ibn Ulayya', death: 193, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['غندر', 'محمد بن جعفر غندر', 'محمد بن جعفر'], latin: 'Ghundar', death: 193, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['ابو بكر بن عياش'], latin: 'Abu Bakr ibn Ayyash', death: 193, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['عبد الوهاب الثقفي', 'عبد الوهاب بن عبد المجيد'], latin: 'Abd al-Wahhab al-Thaqafi', death: 194, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['حفص بن غياث'], latin: 'Hafs ibn Ghiyath', death: 194, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['ابن ابي عدي', 'محمد بن ابي عدي'], latin: 'Muhammad ibn Abi Adi', death: 194, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['ابو معاويه', 'ابو معاويه الضرير', 'محمد بن خازم'], latin: 'Abu Mu\'awiya al-Darir', death: 195, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['محمد بن فضيل', 'ابن فضيل'], latin: 'Muhammad ibn Fudayl', death: 195, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['معاذ بن معاذ'], latin: 'Mu\'adh ibn Mu\'adh', death: 196, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['وكيع', 'وكيع بن الجراح'], latin: 'Waki\' ibn al-Jarrah', death: 197, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['ابن وهب', 'عبد الله بن وهب'], latin: 'Abdullah ibn Wahb', death: 197, gen: 'muhaddith', origin: 'مصر' },
  { names: ['يحيي بن سعيد القطان', 'يحيي القطان'], latin: 'Yahya ibn Sa\'id al-Qattan', death: 198, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['عبد الرحمن بن مهدي', 'ابن مهدي'], latin: 'Abd al-Rahman ibn Mahdi', death: 198, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['سفيان بن عيينه', 'ابن عيينه'], latin: 'Sufyan ibn Uyayna', death: 198, gen: 'muhaddith', origin: 'مكة' },
  { names: ['عبد الله بن نمير'], latin: 'Abdullah ibn Numayr', death: 199, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['ابو ضمره', 'انس بن عياض'], latin: 'Anas ibn Iyad Abu Damra', death: 200, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['ابو اسامه', 'حماد بن اسامه'], latin: 'Abu Usama Hammad ibn Usama', death: 201, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['يحيي بن ادم'], latin: 'Yahya ibn Adam', death: 203, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['ابو داود الطيالسي', 'سليمان بن داود الطيالسي'], latin: 'Abu Dawud al-Tayalisi', death: 204, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['الشافعي', 'محمد بن ادريس الشافعي'], latin: 'al-Shafi\'i', death: 204, gen: 'muhaddith', origin: 'مصر' },
  { names: ['روح بن عباده'], latin: 'Rawh ibn Ubada', death: 205, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['يزيد بن هارون'], latin: 'Yazid ibn Harun', death: 206, gen: 'muhaddith', origin: 'واسط' },
  { names: ['وهب بن جرير'], latin: 'Wahb ibn Jarir', death: 206, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['عبد الرزاق', 'عبد الرزاق بن همام'], latin: 'Abd al-Razzaq', death: 211, gen: 'muhaddith', origin: 'اليمن' },
  { names: ['محمد بن يوسف الفريابي', 'الفريابي'], latin: 'Muhammad ibn Yusuf al-Firyabi', death: 212, gen: 'muhaddith', origin: 'الشام' },
  { names: ['حجاج بن منهال'], latin: 'Hajjaj ibn Minhal', death: 217, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['عبد الله بن يوسف', 'عبد الله بن يوسف التنيسي'], latin: 'Abdullah ibn Yusuf al-Tinnisi', death: 218, gen: 'muhaddith', origin: 'مصر' },
  { names: ['ابو نعيم', 'الفضل بن دكين'], latin: 'Abu Nu\'aym al-Fadl ibn Dukayn', death: 219, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['عفان', 'عفان بن مسلم'], latin: 'Affan ibn Muslim', death: 220, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['ادم', 'ادم بن ابي اياس'], latin: 'Adam ibn Abi Iyas', death: 220, gen: 'muhaddith', origin: 'الشام' },
  { names: ['عبدان', 'عبد الله بن عثمان عبدان'], latin: 'Abdan', death: 221, gen: 'muhaddith', origin: 'خراسان' },
  { names: ['القعنبي', 'عبد الله بن مسلمه', 'عبد الله بن مسلمه القعنبي', 'عبد الله بن مسلمه بن قعنب'], latin: 'al-Qa\'nabi', death: 221, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['ابو اليمان', 'الحكم بن نافع', 'ابو اليمان الحكم بن نافع'], latin: 'Abu al-Yaman al-Hakam ibn Nafi\'', death: 222, gen: 'muhaddith', origin: 'الشام' },
  { names: ['موسي بن اسماعيل', 'موسي بن اسماعيل التبوذكي', 'ابو سلمه التبوذكي'], latin: 'Musa ibn Isma\'il al-Tabudhaki', death: 223, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['سليمان بن حرب'], latin: 'Sulayman ibn Harb', death: 224, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['ابو معمر', 'عبد الله بن عمرو ابو معمر'], latin: 'Abu Ma\'mar al-Minqari', death: 224, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['اسماعيل بن ابي اويس', 'اسماعيل', 'ابن ابي اويس'], latin: 'Isma\'il ibn Abi Uways', death: 226, gen: 'muhaddith', origin: 'المدينة', ambiguous: ['اسماعيل'] },
  { names: ['يحيي بن يحيي', 'يحيي بن يحيي النيسابوري'], latin: 'Yahya ibn Yahya al-Naysaburi', death: 226, gen: 'muhaddith', origin: 'نيسابور' },
  { names: ['ابو الوليد', 'ابو الوليد الطيالسي', 'هشام بن عبد الملك'], latin: 'Abu al-Walid al-Tayalisi', death: 227, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['سعيد بن منصور'], latin: 'Sa\'id ibn Mansur', death: 227, gen: 'muhaddith', origin: 'مكة' },
  { names: ['محمد بن الصباح'], latin: 'Muhammad ibn al-Sabbah', death: 227, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['مسدد', 'مسدد بن مسرهد'], latin: 'Musaddad ibn Musarhad', death: 228, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['يحيي بن بكير', 'يحيي بن عبد الله بن بكير'], latin: 'Yahya ibn Bukayr', death: 231, gen: 'muhaddith', origin: 'مصر' },
  { names: ['عمرو الناقد', 'عمرو بن محمد الناقد'], latin: 'Amr al-Naqid', death: 232, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['يحيي بن معين'], latin: 'Yahya ibn Ma\'in', death: 233, gen: 'rijal', origin: 'بغداد' },
  { names: ['علي بن المديني', 'علي بن عبد الله', 'علي بن عبد الله المديني'], latin: 'Ali ibn al-Madini', death: 234, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['زهير بن حرب', 'ابو خيثمه'], latin: 'Zuhayr ibn Harb', death: 234, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['محمد بن عبد الله بن نمير'], latin: 'Muhammad ibn Abdullah ibn Numayr', death: 234, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['محمد بن ابي بكر المقدمي', 'محمد بن ابي بكر'], latin: 'Muhammad ibn Abi Bakr al-Muqaddami', death: 234, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['ابو بكر بن ابي شيبه', 'عبد الله بن محمد بن ابي شيبه'], latin: 'Abu Bakr ibn Abi Shayba', death: 235, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['سهل بن عثمان'], latin: 'Sahl ibn Uthman', death: 235, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['علي بن محمد', 'علي بن محمد الطنافسي'], latin: 'Ali ibn Muhammad al-Tanafisi', death: 235, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['محمد بن حاتم', 'محمد بن حاتم بن ميمون'], latin: 'Muhammad ibn Hatim', death: 236, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['ابراهيم بن المنذر', 'ابراهيم بن المنذر الحزامي'], latin: 'Ibrahim ibn al-Mundhir', death: 236, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['ابو كامل', 'ابو كامل الجحدري', 'فضيل بن حسين'], latin: 'Abu Kamil al-Jahdari', death: 237, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['اسحاق بن ابراهيم', 'اسحاق بن راهويه', 'اسحاق', 'اسحاق بن ابراهيم الحنظلي'], latin: 'Ishaq ibn Rahwayh', death: 238, gen: 'muhaddith', origin: 'نيسابور', ambiguous: ['اسحاق'] },
  { names: ['محمد بن عبيد الغبري'], latin: 'Muhammad ibn Ubayd al-Ghubari', death: 238, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['عثمان بن ابي شيبه'], latin: 'Uthman ibn Abi Shayba', death: 239, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['محمود بن غيلان'], latin: 'Mahmud ibn Ghaylan', death: 239, gen: 'muhaddith', origin: 'مرو' },
  { names: ['قتيبه', 'قتيبه بن سعيد'], latin: 'Qutayba ibn Sa\'id', death: 240, gen: 'muhaddith', origin: 'خراسان' },
  { names: ['سويد بن نصر'], latin: 'Suwayd ibn Nasr', death: 240, gen: 'muhaddith', origin: 'مرو' },
  { names: ['سويد بن سعيد'], latin: 'Suwayd ibn Sa\'id', death: 240, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['احمد', 'احمد بن حنبل', 'احمد بن محمد بن حنبل'], latin: 'Ahmad ibn Hanbal', death: 241, gen: 'muhaddith', origin: 'بغداد', ambiguous: ['احمد'] },
  { names: ['عبيد الله بن سعيد', 'ابو قدامه'], latin: 'Ubaydullah ibn Sa\'id', death: 241, gen: 'muhaddith', origin: 'نيسابور' },
  { names: ['الحسن بن علي', 'الحسن بن علي الخلال', 'الحسن بن علي الحلواني'], latin: 'al-Hasan ibn Ali al-Khallal', death: 242, gen: 'muhaddith', origin: 'مكة' },
  { names: ['محمد بن رمح'], latin: 'Muhammad ibn Rumh', death: 242, gen: 'muhaddith', origin: 'مصر' },
  { names: ['ابو مصعب', 'ابو مصعب الزهري'], latin: 'Abu Mus\'ab al-Zuhri', death: 242, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['هناد', 'هناد بن السري'], latin: 'Hannad ibn al-Sari', death: 243, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['هارون بن عبد الله', 'هارون بن عبد الله الحمال'], latin: 'Harun ibn Abdullah al-Hammal', death: 243, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['حرمله', 'حرمله بن يحيي'], latin: 'Harmala ibn Yahya', death: 244, gen: 'muhaddith', origin: 'مصر' },
  { names: ['علي بن حجر', 'علي بن حجر السعدي'], latin: 'Ali ibn Hujr', death: 244, gen: 'muhaddith', origin: 'مرو' },
  { names: ['احمد بن منيع'], latin: 'Ahmad ibn Mani\'', death: 244, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['حميد بن مسعده'], latin: 'Humayd ibn Mas\'ada', death: 244, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['اسحاق بن موسي', 'اسحاق بن موسي الانصاري'], latin: 'Ishaq ibn Musa al-Ansari', death: 244, gen: 'muhaddith', origin: 'المدينة' },
  { names: ['هشام بن عمار'], latin: 'Hisham ibn Ammar', death: 245, gen: 'muhaddith', origin: 'الشام' },
  { names: ['محمد بن رافع'], latin: 'Muhammad ibn Rafi\'', death: 245, gen: 'muhaddith', origin: 'نيسابور' },
  { names: ['احمد بن عبده', 'احمد بن عبده الضبي'], latin: 'Ahmad ibn Abda al-Dabbi', death: 245, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['محمد بن عبد الاعلي', 'محمد بن عبد الاعلي الصنعاني'], latin: 'Muhammad ibn Abd al-A\'la', death: 245, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['اسماعيل بن موسي', 'اسماعيل بن موسي الفزاري'], latin: 'Isma\'il ibn Musa al-Fazari', death: 245, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['ابو كريب', 'ابو كريب محمد بن العلاء', 'محمد بن العلاء'], latin: 'Abu Kurayb Muhammad ibn al-Ala\'', death: 248, gen: 'muhaddith', origin: 'الكوفة' },
  { names: ['يحيي بن حبيب', 'يحيي بن حبيب بن عربي'], latin: 'Yahya ibn Habib ibn Arabi', death: 248, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['احمد بن صالح', 'احمد بن صالح المصري'], latin: 'Ahmad ibn Salih al-Misri', death: 248, gen: 'muhaddith', origin: 'مصر' },
  { names: ['محمد بن سلمه', 'محمد بن سلمه المرادي'], latin: 'Muhammad ibn Salama al-Muradi', death: 248, gen: 'muhaddith', origin: 'مصر' },
  { names: ['عبد بن حميد'], latin: 'Abd ibn Humayd', death: 249, gen: 'muhaddith', origin: 'خراسان' },
  { names: ['عمرو بن علي', 'عمرو بن علي الفلاس'], latin: 'Amr ibn Ali al-Fallas', death: 249, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['ابو الطاهر', 'احمد بن عمرو بن السرح'], latin: 'Abu al-Tahir ibn al-Sarh', death: 250, gen: 'muhaddith', origin: 'مصر' },
  { names: ['نصر بن علي', 'نصر بن علي الجهضمي'], latin: 'Nasr ibn Ali al-Jahdami', death: 250, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['اسحاق بن منصور', 'اسحاق بن منصور الكوسج'], latin: 'Ishaq ibn Mansur al-Kawsaj', death: 251, gen: 'muhaddith', origin: 'نيسابور' },
  { names: ['محمد بن بشار', 'بندار', 'محمد بن بشار بندار'], latin: 'Muhammad ibn Bashshar Bundar', death: 252, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['محمد بن المثني', 'ابو موسي محمد بن المثني'], latin: 'Muhammad ibn al-Muthanna', death: 252, gen: 'muhaddith', origin: 'البصرة' },
  { names: ['يعقوب بن ابراهيم الدورقي', 'يعقوب الدورقي'], latin: 'Ya\'qub al-Dawraqi', death: 252, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['هارون بن سعيد', 'هارون بن سعيد الايلي'], latin: 'Harun ibn Sa\'id al-Ayli', death: 253, gen: 'muhaddith', origin: 'مصر' },
  { names: ['محمد بن يحيي', 'محمد بن يحيي الذهلي'], latin: 'Muhammad ibn Yahya al-Dhuhli', death: 258, gen: 'muhaddith', origin: 'نيسابور' },
  { names: ['حجاج بن الشاعر', 'حجاج بن يوسف بن الشاعر'], latin: 'Hajjaj ibn al-Sha\'ir', death: 259, gen: 'muhaddith', origin: 'بغداد' },
  { names: ['عبد الرحمن بن بشر', 'عبد الرحمن بن بشر بن الحكم'], latin: 'Abd al-Rahman ibn Bishr', death: 260, gen: 'muhaddith', origin: 'نيسابور' },
  { names: ['يونس بن عبد الاعلي'], latin: 'Yunus ibn Abd al-A\'la', death: 264, gen: 'muhaddith', origin: 'مصر' },
  { names: ['ابو زرعه الرازي'], latin: 'Abu Zur\'a al-Razi', death: 264, gen: 'muhaddith', origin: 'الري' },
  { names: ['الربيع بن سليمان'], latin: 'al-Rabi\' ibn Sulayman', death: 270, gen: 'muhaddith', origin: 'مصر' },
  { names: ['ابو حاتم الرازي'], latin: 'Abu Hatim al-Razi', death: 277, gen: 'muhaddith', origin: 'الري' },
  { names: ['الدارمي', 'عبد الله بن عبد الرحمن الدارمي', 'عبد الله بن عبد الرحمن'], latin: 'al-Darimi', death: 255, gen: 'muhaddith', origin: 'سمرقند' },
];
